### ISSUE TITLE
sendMessage always has timestamp: 0 on fedmsg

### ISSUE THREAD

**Issue by johnbieren** [jenkinsci/jms-messaging-plugin#125]
Using jms-messaging-1.1.5 (but there are no changes to src/main/java/com/redhat/jenkins/plugins/ci/messaging/data/FedmsgMessage.java from 1.1.5 to 1.1.7), messages sent via fedmsg always have timestamp: 0 in their messages. It is a little hard to spot, since datagrepper will add its own timestamp. However, it seems just calling ```sendMessage``` prints back the message that is sent out, which includes timestamp: 0. This is a problem because things (e.g. irc notifications) go off this timestamp, and it is resulting in the irc notifications saying XX years ago. When using the activeMQ messages, I don't see a timestamp value auto injected at all (I don't know of any issues with the activeMQ sendMessage). 

For examples, go to this job
https://jenkins-continuous-infra.apps.ci.centos.org/job/fedora-task-pipeline-trigger/
click any of the successful builds console output, and look for
```
Sending message for job 'fedora-task-pipeline-trigger'.
JSON message body:
```
You will see timestamp: 0

Related fedora-ci issue: https://pagure.io/fedora-ci/messages/issue/53

**Comment by scoheb** [comment]
Released in v1.1.8
