### ISSUE TITLE
Support RabbitMQ as a Provider

### ISSUE THREAD

**Issue by bstinsonmhk** [jenkinsci/jms-messaging-plugin#132]
We currently use the JMS Messaging Plugin in Jenkins Pipelines with the Fedmsg Provider for the Fedora CI project (https://docs.fedoraproject.org/en-US/ci/)

We are planning on migrating our messaging system to RabbitMQ, and would like to continue using the JMS Messaging Plugin in the same workflow (same topics, same certificate-style authentication, etc.)

This ticket is to track the progress on: 

- [ ] A simple send/receive client written in java (we'll post a link in the comments here)
- [ ] The skeleton of the RabbitMQ JMS plugin provider itself
- [ ] A container image to use when writing tests against the RabbitMQ provider (will be contributed to this repo)

We think that we should start writing the simple java client using this library:
(https://www.rabbitmq.com/jms-client.html)

**Comment by scoheb** [comment]
Created initial skeleton here: https://github.com/jenkinsci/jms-messaging-plugin/tree/rabbitmq-skeleton

**Comment by Zlopez** [comment]
@scoheb 
I started working on the simple client implementation and I have a question:

How the `com.redhat.jenkins.plugins.ci.messaging.RabbitMQMessagingWorker.subscribe` should work? I looked at the FedMsg and ActiveMQ implementation and I don't see any callback that will trigger job when something is received.
Without comments or documentation it's hard to understand how this method works, could you explain it to me?

**Comment by scoheb** [comment]
```CITriggerThread.java``` calls ```messagingWorker.receive(jobname, providerData);```
```receive()``` then calls ```JMSMessagingWorker.receive()``` which your initial ```subscribe``` would have setup.

FYI @ggallen

**Comment by Zlopez** [comment]
Thanks for explanation, now I know that I need to override `receive`. :-)

My first understanding was that subscribe is listening to any new message and some callback is called when the message is received.

**Comment by Zlopez** [comment]
The https://github.com/jenkinsci/jms-messaging-plugin/pull/154 is already merged, this issue could be closed

**Comment by bstinsonmhk** [comment]
This can indeed be closed!
