### ISSUE TITLE
CI Triggered jobs blank out parameters

### ISSUE THREAD

**Issue by Lorquas** [jenkinsci/jms-messaging-plugin#137]
I'm seeing an issue similar to https://github.com/jenkinsci/jms-messaging-plugin/issues/134 except for `stringParam` and `textParam` (and possibly other param types?).

using a freestyle job with DSL like: 
```
job('reproducer'){
  parameters {
    stringParam('CI_MESSAGE', null, 'UMB CI Message')
    stringParam( 'NAME', 'world', 'Default name.') // also happens for textParam
  }
  steps {
    shell { command('echo hello $NAME') }
  }
}
```
with an additional ciBuildTrigger added.   Whenever this job is triggered by the CI message, all params are blanked out (defaults ignored) with the exception of the `CI_MESSAGE` parameter.
Our current work around is to copy the value of `CI_MESSAGE` and manually trigger a new run with the previous `CI_MESSAGE`.

**Comment by scoheb** [comment]
so the problem is that the defaults are simply ignored if not specified WHEN the job is triggered by the plugin?

**Comment by Lorquas** [comment]
@scoheb correct.  If the above job were triggered by the plugin you'd simply see "hello "  in the console output instead of "hello world"

**Comment by scoheb** [comment]
@Lorquas I have a snapshot version you can try that has a fix: https://ci.jenkins.io/job/Plugins/job/jms-messaging-plugin/job/PR-138/2/artifact/target/jms-messaging.hpi

If you can, please give it a try.

**Comment by Lorquas** [comment]
@scoheb tested this this morning and it all seemed to work for text/strings/bools. Thanks!
