### ISSUE TITLE
MS Messaging plugin for Jenkins does not use default parameters of job.

### ISSUE THREAD

**Issue by ggallen** [jenkinsci/jms-messaging-plugin#140]
It seems like trigger sendCIMessage is not able to use default job parameters, when this job is triggered via such message. I can only see in build parameters CI_MESSAGE & MESSAGE_HEADERS.

If I just build job manually, all default values are used properly (empty CI_MESSAGE) as expected.

Please see attached pictures.

Code can be found here:

https://bitbucket.org/msgqe/msg-qe-ci-jobs-broker/src/mt_amq6_dsl/jenkins/config/cci/dsl/

(I am beginner with pipelines and jobDSL, so excuse my poor code.)

**Comment by scoheb** [comment]
This should be fixed as of version 1.1.10.
