### ISSUE TITLE
Boolean parameters are not set by JMS properties

### ISSUE THREAD

**Issue by vmuzikar** [jenkinsci/jms-messaging-plugin#141]
**Environment:**
* A Jenkins Job *A* that has a boolean parameter and is configured to be triggered by a CI message.
* A Jenkins Job *B* (which is actually a pipeline) that sends CI messages.
* JMS Messaging plugin version: 1.1.9
* Jenkins version: 2.121.3

When we send a message from *B* that contains a boolean property, job *A* is triggered but its boolean parameter is not set by the boolean property. The *A*'s boolean parameter is always set to its default value regardless the CI message.

This works for us with string parameters/properties, so this concerns only boolean.

Version 1.1.2 works just fine with boolean parameters.

**Comment by scoheb** [comment]
So your CI_MESSAGE parameter is a `boolean` ?

can you share the config.xml files from JobA and JobB?

@ggallen FYI

**Comment by vmuzikar** [comment]
@scoheb We don't use CI_MESSAGE parameter. We're using the CI Message Properties which are "mapped" to job parameters. We were able to reproduce it with as simple jobs as possible.

Job *A* definition: https://gist.github.com/vmuzikar/da74799cacc166cf13e9fd100fb09815

Job *B* is a pipeline which basically just calls something like this:
```groovy
sendCIMessage(
    providerName: 'UMB',
    overrides: ['topic': topic],
    messageContent: content,
    messageProperties: 'STR_PARAM=kocka pes\nFOO_BAR=true',
    messageType: 'Custom'
)
```

`STR_PARAM` in *A* is then set to "kocka pes" whereas `FOO_BAR` is left set to false.
