### ISSUE TITLE
Configuration not loaded for CI Notifier build step and post-build action.

### ISSUE THREAD

**Issue by ggallen** [jenkinsci/jms-messaging-plugin#146]
The configuration is not being loaded correctly for either the CI Notifier build stop nor the post build action.  

To reproduce, just add one of each to a job, hit apply, then refresh. The changes disappear, but they are still in the config.xml.

**Comment by Zlopez** [comment]
I can confirm this issue and it is happening only for publishers.

I even noticed the same issue in RabbitMQ pull request #154

**Comment by scoheb** [comment]
This will be fixed by #187

**Comment by scoheb** [comment]
Fix released in version 1.1.16
