### ISSUE TITLE
Using CI trigger on parametrized builds strip all non text parameters

### ISSUE THREAD

**Issue by scoheb** [jenkinsci/jms-messaging-plugin#178]
When using CI trigger on Jenkins parametrized build strips all non text parameters like selectboxes.
We use selectbox fields with options provided, so the first option is used as a default.

**Comment by scoheb** [comment]
Are you expecting to see the Select/Choice parameter to be set via the incoming message? 
Or are you just wanting to ensure that the default Select/Choice parameters are set to their default values?

**Comment by cardil** [comment]
> Are you expecting to see the Select/Choice parameter to be set via the incoming message?
> Or are you just wanting to ensure that the default Select/Choice parameters are set to their default values?

I want to ensure that the defaults are used, for now.

**Comment by cardil** [comment]
It also relates to `boolean` params. The default value for a field should be used.

**Comment by scoheb** [comment]
So #179 will ensure defaults are chosen for `choice` params
The current version already handles `boolean` params. 
Are you also seeing an issue with `boolean`?

**Comment by scoheb** [comment]
@cardil Snapshot binary available for testing here: https://ci.jenkins.io/job/Plugins/job/jms-messaging-plugin/job/PR-179/3/artifact/plugin/target/jms-messaging.hpi

**Comment by cardil** [comment]
I didn't see it for booleans. Just presumed it must be similar
