### ISSUE TITLE
Selectors disappeared from UI after update to 1.1.16

### ISSUE THREAD

**Issue by Michkov** [jenkinsci/jms-messaging-plugin#190]
Selectors for ActiveMQ and Message Checks for Fedmsg disappeared from UI after saving configuration.
Also Topic override is changed on every configuration change.

Steps to reproduce:
1) create new Freestyle project (or any project type)
2) Enable CI event
3) Select Active MQ based provider
4) Override provider -> select your own
5) Set JMS selector
6) Click on Save
7) Click on Configure

Current results:

- JMS selector is empty
- Override provider changed

Expected results:
- Configuration is the same as before save.

Version: 1.1.16
Workaround - downgrade to 1.1.3

**Comment by scoheb** [comment]
Fixed in release 1.1.17.

Thanks for reporting!
