### ISSUE TITLE
RabbitMQ is not creating queues

### ISSUE THREAD

**Issue by Michkov** [jenkinsci/jms-messaging-plugin#200]
I want to use fedora-messaging for triggering my jobs. I am getting error: 
```
Eexception raised while subscribing job 'test-2', retrying in 1 minutes.
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '9d1eea0c-ca87-11ea-a1b5-0050b6b83acd' in vhost '/public_pubsub', class-id=50, method-id=20)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:522)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:599)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Configuration:
Connection Properties:

- Name: fedora-messaging
- Hostname: rabbitmq.fedoraproject.org
- Port Number: 5671
- Virtual Host: /public_pubsub
- Topic:
- Exchange: amq.topic
- Queue:
- Authentication Method: SSL Certificate Authentication
  - User name:
  - Key store: /var/lib/jenkins/fedora-messaging/keystore.ks
  - Key store password: changeit
  - Trust store: /var/lib/jenkins/fedora-messaging/cacert.ts
  - Trust store password: changeit

Job configuration:
- CI event:
  fedora-messaging
  Topic name: io.pagure.prod.pagure.pull-request.comment.added
  Queue name: 9d1eea0c-ca87-11ea-a1b5-0050b6b83acd

Seems that plugin is not creating Queue. When I create Queue manually then it works.

Plugin version: 1.1.18
Jenkins version: 2.222.1

**Comment by Zlopez** [comment]
I think we already had similar issue in the Fedora infra, the rabbitmq in fedoraproject.org doesn't allow automatic creation of queues AFAIK.

So you need to have it created in advance.

**Comment by Michkov** [comment]
Fedora is allowing to create it but it has to be in uuid format. When I am using 'fedora-messaging' command it's using the same certificate and queue is created - https://fedora-messaging.readthedocs.io/en/latest/quick-start.html#fedora-s-public-broker
