### ISSUE TITLE
messageId property has malformed format

### ISSUE THREAD

**Issue by Andrei-Stepanov** [jenkinsci/jms-messaging-plugin#218]
Hello,

The bug is in RabbitMQ part of this plugin.
Messages sent with jms-messaging-plugin to RabbitMQ fedora broker have incorrect `messageId` property.
Property `messageId` has prefix : year-UUID.
This is bug.

From : https://fedora-messaging.readthedocs.io/en/stable/wire-format.html#message-id

```
The message ID field MUST be a version 4 UUID as a standard hexadecimal digit string (e.g. f81d4fae-7dec-11d0-a765-00a0c91e6bf6)
```

https://github.com/jenkinsci/jms-messaging-plugin/blob/master/plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/data/RabbitMQMessage.java#L75

has code:

```
daee7469 (Oliver Gondža 2020-09-01 20:52:34 +0200 75)             this.msgId = Calendar.getInstance().get(1) + "-" + UUID.randomUUID().toString();
```

What impact is: 

- messages are malformed.
- Broker can easily drop messages that doesn't comply with requirements.
- There is internal logic for datagrepper, where it adds `year` to messageID too.  --->  mess with messageID. 

More info you can find at: https://pagure.io/fedora-infrastructure/issue/10084

**Comment by olivergondza** [comment]
No idea why it is being done this way: https://github.com/jenkinsci/jms-messaging-plugin/pull/154/files#diff-55442404b12c5e36812d6d2244165fb065f02677aa22a00fc7df400e4b4011b2R98

@Zlopez, what is the motivation to prefix the auto-generated IDs? Thanks!

**Comment by Zlopez** [comment]
@olivergondza If you look at [message in datagrepper](https://datagrepper-monitor-dashboard.app.os.fedoraproject.org/id?id=2021-1eda6f88-7381-4f30-9be3-3e3d96a739a3&is_raw=true&size=extra-large) you can see that message id is prefixed by year, not sure why, but I try to mimic the fedora messaging publisher behavior as best as I can. It's possible that the year is added by rabbitmq server latter and the publisher shouldn't do it.

If the year is causing problem, it could be probably safely removed.
