### ISSUE TITLE
"highmem" node type use to be revised

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/jms-messaging-plugin#226]
How much memory is needed to build this plugin?

The "highmem" node type used [in the Jenkinsfile](https://github.com/jenkinsci/jms-messaging-plugin/blob/master/Jenkinsfile) seems oversized.

**Comment by olivergondza** [comment]
Good point, removed in https://github.com/jenkinsci/jms-messaging-plugin/commit/b288322fbf1124a440aa4a886e94e409fbc9fe71
